vich_uploader:
    db_driver: orm

    mappings:
        car:
            uri_prefix: /images/car
            upload_destination: "%kernel.project_dir%/public/images/car"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        service:
            uri_prefix: /images/service
            upload_destination: "%kernel.project_dir%/public/images/service"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        various:
            uri_prefix: /images/various
            upload_destination: "%kernel.project_dir%/public/images/various"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer